# Generated by Django 3.2.6 on 2021-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitydonation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istitution_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type', models.TextField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default='Fundacja')),
                ('categories', models.ManyToManyField(to='charitydonation.Category')),
            ],
        ),
    ]
