# Generated by Django 3.1 on 2021-09-13 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charitydonation', '0002_auto_20210909_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(default=datetime.time),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(),
        ),
    ]
