# Generated by Django 3.2.6 on 2021-08-25 16:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charitydonation', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.TextField()),
                ('pick_up_date', models.DateTimeField(verbose_name=datetime.date)),
                ('pick_up_time', models.IntegerField()),
                ('pick_up_comment', models.TextField()),
                ('categories', models.ManyToManyField(to='charitydonation.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charitydonation.institution')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
